### ISSUE TITLE
length error 

### ISSUE THREAD

**Issue by alphaleadership** [dogancelik/twdl#4] opened 2022-06-24 10:02 UTC
```
let mediaCount = mediaData.media.length;
                                         ^

TypeError: Cannot read properties of undefined (reading 'length')
    at joinResolved (d:\node\node_modules\twdl\out\index.js:140:42)
    at tryCatcher (d:\node\node_modules\twdl\node_modules\bluebird\js\release\util.js:16:23)
    at Holder$4._callFunction (eval at generateHolderClass (d:\node\node_modules\twdl\node_modules\bluebird\js\release\join.js:91:16), <anonymous>:14:44)
    at Holder$4.checkFulfillment (eval at generateHolderClass (d:\node\node_modules\twdl\node_modules\bluebird\js\release\join.js:91:16), <anonymous>:29:30)
    at Promise.eval (eval at thenCallback (d:\node\node_modules\twdl\node_modules\bluebird\js\release\join.js:13:16), <anonymous>:6:20)    
    at Promise._settlePromise (d:\node\node_modules\twdl\node_modules\bluebird\js\release\promise.js:601:21)
    at Promise._settlePromise0 (d:\node\node_modules\twdl\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (d:\node\node_modules\twdl\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (d:\node\node_modules\twdl\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (d:\node\node_modules\twdl\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (d:\node\node_modules\twdl\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (d:\node\node_modules\twdl\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (node:internal/timers:466:21)
```

**Comment by alphaleadership** [comment] 2022-06-24 10:05
my source code 
```js

const importer =(name)=>{
    return require("d:\\node\\node_modules\\"+name)
} 

const fs=require("fs")

const list=(path)=>{return fs.readFileSync(path).toString().split("\n")}
let array=list('./url_vidéo.txt')
const twdl = importer('twdl');

const tweetUrls = array;

const options = {
	embed: false
};
async function main(tweetUrls) {
    await twdl.downloadUrls(tweetUrls, options);

    console.log('Finished');   
}
main(list('./url_vidéo.txt'))
```

**Comment by dogancelik** [comment] 2022-06-25 23:15
Hello @alphaleadership, thank you for opening this issue, I am aware of the problem as well.
It looks like Twitter has dropped the old HTML design so I need re-adjust the query selectors in `twitterApi.ts`.
I am working on it and I will release a new version today hopefully.

**Comment by dogancelik** [comment] 2022-06-26 04:09
@alphaleadership I published a new version. Can you update *twdl* to `v2.5.1` and try the command below:

```
npm install twdl@latest
```

**Comment by alphaleadership** [comment] 2022-06-26 17:09
Thanks

Le dim. 26 juin 2022 à 06:09, Doğan Çelik ***@***.***> a
écrit :

**Comment by alphaleadership** [comment] 2022-07-16 10:58
use other modules

**Comment by dogancelik** [comment] 2022-07-30 21:41
The problem is fixed so I'm closing this issue.

**Closed as completed by dogancelik** 2022-07-30 21:41 UTC
